In [40]:
import numpy as np
import math

In [41]:
X = np.array([100, 80, 75, 77, 89, 33, 45, 25, 65, 17, 30, 24, 57, 55, 70, 75, 65, 84, 90, 150])
X.sort()
X


array([ 17,  24,  25,  30,  33,  45,  55,  57,  65,  65,  70,  75,  75,
        77,  80,  84,  89,  90, 100, 150])

In [42]:
n = X.shape
n

(20,)

In [47]:
l = len(X)

### Даны значения зарплат из выборки выпускников: 100, 80, 75, 77, 89, 33, 45, 25, 65, 17, 30, 24, 57, 55, 70, 75, 65, 84, 90, 150. Посчитать (желательно без использования статистических методов наподобие std, var, mean) среднее арифметическое, среднее квадратичное отклонение, смещенную и несмещенную оценки дисперсий для данной выборки.

In [43]:
#Ср. арифметическое
mean = sum(X)/n
mean

array([65.3])

In [44]:
#Cр. квадратичн. откл.
std = math.sqrt(sum((X-mean)**2)/n)
std

30.823854398825596

In [45]:
#Смещенная дисперсия
S = sum((X-mean)**2)/n
S

array([950.11])

In [49]:
#Несмещенная
S2 = sum((X-mean)**2)/(l-1)
S2

1000.1157894736842